exports.up = (pgm) => {
  pgm.createTable("Temp", {
    id: { type: "serial", primaryKey: true },
    nome: { type: "text", notNull: true },
    codigo: { type: "text", notNull: true },
    multi: { type: "numeric", notNull: true },
    r: { type: "numeric", notNull: true },
    data: { type: "timestamptz", notNull: true },
    comissao: { type: "numeric", notNull: true },
    v01: { type: "numeric" },
    v02: { type: "numeric" },
    v03: { type: "numeric" },
    v04: { type: "numeric" },
    v05: { type: "numeric" },
    v06: { type: "numeric" },
    v07: { type: "numeric" },
    v08: { type: "numeric" },
    v09: { type: "numeric" },
    v10: { type: "numeric" },
    v11: { type: "numeric" },
    v12: { type: "numeric" },
    v13: { type: "numeric" },
    v14: { type: "numeric" },
    v15: { type: "numeric" },
    v16: { type: "numeric" },
    v17: { type: "numeric" },
    v18: { type: "numeric" },
    v19: { type: "numeric" },
    v20: { type: "numeric" },
    v21: { type: "numeric" },
    v22: { type: "numeric" },
    v23: { type: "numeric" },
    v24: { type: "numeric" },
    v25: { type: "numeric" },
    v26: { type: "numeric" },
    v27: { type: "numeric" },
    v28: { type: "numeric" },
  });
};

exports.down = false;
